#students score

name=input("what is your name")
print(type(name))
science=input("what is your science score")
print(type(science))
english=input("what is your english score")
print(type(english))
Math=input("what is you maths score")
print(type(Math))
sc=input("what is your sc score ")
print(type(sc))
cs=input("what is your cs score ")
print(type(cs))
total=input("what is your total marks")
print(total)